// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQrtWFQKz91XkpFzdeCBmsjDHsHk97OmA',
    appId: '1:468743634039:web:4b43b7e6a62cff6be35a72',
    messagingSenderId: '468743634039',
    projectId: 'socialapp-af773',
    authDomain: 'socialapp-af773.firebaseapp.com',
    storageBucket: 'socialapp-af773.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHrdb6xx6oESolYPPpFQ2RvxbcBsXCWeA',
    appId: '1:468743634039:android:218f27dbf29a5996e35a72',
    messagingSenderId: '468743634039',
    projectId: 'socialapp-af773',
    storageBucket: 'socialapp-af773.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLPHrqOoLbTyQBCFS988s1usYWGosdhf0',
    appId: '1:468743634039:ios:409407bc5d05b54ae35a72',
    messagingSenderId: '468743634039',
    projectId: 'socialapp-af773',
    storageBucket: 'socialapp-af773.appspot.com',
    iosBundleId: 'com.example.socialapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLPHrqOoLbTyQBCFS988s1usYWGosdhf0',
    appId: '1:468743634039:ios:409407bc5d05b54ae35a72',
    messagingSenderId: '468743634039',
    projectId: 'socialapp-af773',
    storageBucket: 'socialapp-af773.appspot.com',
    iosBundleId: 'com.example.socialapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQrtWFQKz91XkpFzdeCBmsjDHsHk97OmA',
    appId: '1:468743634039:web:36cb1d3ef553226fe35a72',
    messagingSenderId: '468743634039',
    projectId: 'socialapp-af773',
    authDomain: 'socialapp-af773.firebaseapp.com',
    storageBucket: 'socialapp-af773.appspot.com',
  );
}
